---
- name: install epel-release
  yum: name=https://dl.fedoraproject.org/pub/epel/7/x86_64/e/epel-release-7-5.noarch.rpm state=present
  sudo: yes

- name: install the 'Development Tools' package group
  yum: name="@Development Tools" state=present
  sudo: yes

- name: install policycoreutils-devel for selinux
  yum: name=policycoreutils-devel state=present
  sudo: yes

- name: install devel packages for ruby compilation
  yum: name=readline-devel,zlib-devel,libyaml-devel,libffi-devel,openssl-devel state=present
  sudo: yes
