---
  - name: create /var/www dir
    file: path=/var/www state=directory
    sudo: yes
  - name: create deployment dir
    file: path=/var/www/{{app_user}} state=directory owner={{app_user}} group={{app_user}}
    sudo: yes
