---
  - name: create deployment dir
    file: path=/home/{{app_user}}/site-{{app_user}} state=directory
    sudo_user: "{{app_user}}"
  - name: create log dir
    file: path=/home/{{app_user}}/site-{{app_user}}/log state=directory
    sudo_user: "{{app_user}}"
  - name: create pids dir
    file: path=/home/{{app_user}}/site-{{app_user}}/pids state=directory
    sudo_user: "{{app_user}}"
  - name: create sockets dir
    file: path=/home/{{app_user}}/site-{{app_user}}/sockets state=directory
    sudo_user: "{{app_user}}"
