---
  - name: install nvm via curl
    shell: $SHELL -lc "curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.25.1/install.sh | bash"
    sudo_user: "{{app_user}}"
  - name: node | install node with version from defaults
    shell: $SHELL -lc "nvm install {{version_node}}"
    sudo_user: "{{app_user}}"
  - name: node | set default version to version from defaults
    shell: $SHELL -lc "nvm alias default {{version_node}}"
    sudo_user: "{{app_user}}"
  - name: node | install bower
    shell: $SHELL -lc "npm install -g bower"
    sudo_user: "{{app_user}}"
