---
- name: install the postgres yum repo
  yum: name=http://yum.postgresql.org/9.4/redhat/rhel-7-x86_64/pgdg-centos94-9.4-1.noarch.rpm state=present
  sudo: yes

- name: install postgres packages
  yum: name=postgresql94,postgresql94-devel,postgresql94-server,postgresql94-contrib,postgresql94-libs disablerepo=* enablerepo=pgdg94 state=present
  sudo: yes

- name: install python-psycopg2
  yum: name=python-psycopg2
  sudo: yes
