---
  - name: app-web-1.service
    template: src=app-web-1.service.j2 dest=/etc/systemd/system/rails-{{app_user}}.service mode=0644
    sudo: yes
  - name: enable app-web-1.service
    service: name=rails-{{app_user}}.service state=started enabled=yes
    sudo: yes
  - name: app nginx config
    template: src=app.conf.j2 dest=/etc/nginx/conf.d/rails-{{app_user}}.conf
    sudo: yes
